// <auto-generated />
using BusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessApi.Migrations
{
    [DbContext(typeof(BusinessApiContext))]
    [Migration("20230401000718_Shops")]
    partial class Shops
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessApi.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("YearsInBusiness")
                        .HasColumnType("int");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Name = "Matilda's Bistro",
                            Type = "Restaurant",
                            YearsInBusiness = 7
                        },
                        new
                        {
                            BusinessId = 2,
                            Name = "Rexi Teacups",
                            Type = "Shop",
                            YearsInBusiness = 10
                        },
                        new
                        {
                            BusinessId = 3,
                            Name = "Matilda Toys",
                            Type = "Shop",
                            YearsInBusiness = 2
                        },
                        new
                        {
                            BusinessId = 4,
                            Name = "Pip's Pizza & Brew",
                            Type = "Restaurant",
                            YearsInBusiness = 4
                        },
                        new
                        {
                            BusinessId = 5,
                            Name = "Bartholomew Pet Shop",
                            Type = "Shop",
                            YearsInBusiness = 22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
